[book]
title = "IFT News"
authors = ["Claire Pinson"]
language = "en"
multilingual = false
src = "reports"

[output.html]
cname = "https://news.free.technology/"
path = "book"
default-theme = "ayu"
no-section-label = true
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/status-im/ift-weekly-news"
git-branch = "master"
sanitize = false

[output.html.fold]
enable = true
level = 0

[output.html.renderers]
html = true
